// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MuLZBkm5wKbDmgw2WldWKkAB-VERYIk',
    appId: '1:610526975342:web:06454707f9eee438791d7f',
    messagingSenderId: '610526975342',
    projectId: 'chat-app-9339f',
    authDomain: 'chat-app-9339f.firebaseapp.com',
    storageBucket: 'chat-app-9339f.appspot.com',
    measurementId: 'G-KXNRWFSEF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHwR17lcE3gW6uAujk5a82O8eBJha3hI',
    appId: '1:610526975342:android:029da0b0a128cdda791d7f',
    messagingSenderId: '610526975342',
    projectId: 'chat-app-9339f',
    storageBucket: 'chat-app-9339f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCercUiw8KJ0SnCTxD7RuTRHPSHnM8RrZ8',
    appId: '1:610526975342:ios:a6dec6060e8c21b9791d7f',
    messagingSenderId: '610526975342',
    projectId: 'chat-app-9339f',
    storageBucket: 'chat-app-9339f.appspot.com',
    iosClientId: '610526975342-4c8kmdi60l3biitrv9ahm8b8liaa04m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCercUiw8KJ0SnCTxD7RuTRHPSHnM8RrZ8',
    appId: '1:610526975342:ios:a6dec6060e8c21b9791d7f',
    messagingSenderId: '610526975342',
    projectId: 'chat-app-9339f',
    storageBucket: 'chat-app-9339f.appspot.com',
    iosClientId: '610526975342-4c8kmdi60l3biitrv9ahm8b8liaa04m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
